proxysql:
  image: proxysql:{{proxysql_image}}
  links:
    - backend1hostgroup0
  ports:
    # ProxySQL admin port for MySQL commands
    - "6032:6032"
    # ProxySQL main port
    - "6033:6033"
    # gdbserver
    - "2345:2345"
  volumes:
    # Sharing the data with 
    - /tmp/proxysql-tests:/opt/proxysql
  privileged: true

backend1hostgroup0:
  image: proxysql:mysql-simple-dump
  environment:
    MYSQL_ROOT_PASSWORD: root
  expose:
    - "3306"
  ports:
    - "13306:3306"
