proxysql:
  build: ../base/proxysql
  links:
    - backend1hostgroup0
  ports:
    - "6032:6032"
    - "6033:6033"
    # gdbserver
    - "2345:2345"
  privileged: true

backend1hostgroup0:
  build: ./mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
  expose:
    - "3306"
  ports:
    - "13306:3306"
